julia --project=. run-experiments.jl SEED=86
julia --project=. run-experiments.jl SEED=29
julia --project=. run-experiments.jl SEED=298
julia --project=. run-experiments.jl SEED=32
julia --project=. run-experiments.jl SEED=26
julia --project=. run-experiments.jl SEED=66
julia --project=. run-experiments.jl SEED=11
julia --project=. run-experiments.jl SEED=374
julia --project=. run-experiments.jl SEED=21
julia --project=. run-experiments.jl SEED=80